import type { Metadata } from "next";
import {Poppins,Montserrat } from "next/font/google";
import "./globals.css";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import Header from "./Components/Header";
import { CircleX, ShoppingBag, ShoppingCart, User, UserCheck } from "lucide-react";
import Image from "next/image";
import Footer1 from "./Components/Footer1";
import Link from "next/link";


const inter = Poppins({
  subsets: ["latin"],
  weight: "400"
});
const inter2 = Montserrat({ subsets: ["latin"],
   variable:'--font-Montserrat'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
   let heart="/Wishlist.png"
  return (
    <html lang="en">
      <body className={`${inter.className} ${inter2.variable}`}>  <Header heart={<Image src={heart}  alt='' width={200} height={200} className=' w-[28px]'></Image>}
    cart={<UserCheck />}
    cart2={<UserCheck className="w-[20px]"/>}
    user={<DropdownMenu>
      <DropdownMenuTrigger><ShoppingCart /></DropdownMenuTrigger>
      <DropdownMenuContent className="text-black bg-white  px-7">
        <DropdownMenuLabel className="flex gap-24"><p className="text-[24px] font-semibold">Shopping Cart</p> <ShoppingBag /></DropdownMenuLabel>
        <DropdownMenuSeparator />
        <DropdownMenuItem className="flex justify-between">
        <Image src="/s1.png" width={100} height={100} alt="/" className='w-[108px] h-[105px] my-2 bg-[#B88E2F] bg-opacity-40 rounded-lg '></Image>
        <div>
          <div><p>Asgaard sofa</p></div>
          <div className="flex gap-3"><span>1</span><span>x</span><span className="text-[#B88E2F]">Rs. 250,000.00</span></div>
        </div>
        <div>
        <CircleX color="#595959" />
        </div>
        </DropdownMenuItem>
        <DropdownMenuItem className="flex justify-between">
        <Image src="/s2.png" width={100} height={100} alt="/" className='w-[108px] h-[105px] my-2 bg-[#B88E2F] bg-opacity-40 rounded-lg '></Image>
        <div>
          <div><p>Asgaard sofa</p></div>
          <div className="flex gap-3"><span>1</span><span>x</span><span className="text-[#B88E2F]">Rs. 250,000.00</span></div>
        </div>
        <div>
        <CircleX color="#595959" />
        </div>
        </DropdownMenuItem>
        <DropdownMenuSeparator className="mt-16"/>
        <DropdownMenuItem className=" flex gap-4"><span className=" px-4 py-1 border-[1.2px] border-black rounded-full"><Link href="/cart">Cart</Link></span ><span className=" px-4 py-1 border-[1.2px] border-black rounded-full"><Link href="/checkout">Checkout</Link></span><span  className=" px-4 py-1 border-[1.2px] border-black rounded-full"><Link href="/productcomparision">Comparison</Link></span></DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
    }
    user2={<DropdownMenu>
      <DropdownMenuTrigger><ShoppingCart className="w-[18px]"/></DropdownMenuTrigger>
      <DropdownMenuContent className="text-black bg-white  px-7">
        <DropdownMenuLabel className="flex gap-24"><p className="text-[24px] font-semibold">Shopping Cart</p> <ShoppingBag /></DropdownMenuLabel>
        <DropdownMenuSeparator />
        <DropdownMenuItem className="flex justify-between">
        <Image src="/s1.png" width={100} height={100} alt="/" className='w-[108px] h-[105px] my-2 bg-[#B88E2F] bg-opacity-40 rounded-lg '></Image>
        <div>
          <div><p>Asgaard sofa</p></div>
          <div className="flex gap-3"><span>1</span><span>x</span><span className="text-[#B88E2F]">Rs. 250,000.00</span></div>
        </div>
        <div>
        <CircleX color="#595959" />
        </div>
        </DropdownMenuItem>
        <DropdownMenuItem className="flex justify-between">
        <Image src="/s2.png" width={100} height={100} alt="/" className='w-[108px] h-[105px] my-2 bg-[#B88E2F] bg-opacity-40 rounded-lg '></Image>
        <div>
          <div><p>Asgaard sofa</p></div>
          <div className="flex gap-3"><span>1</span><span>x</span><span className="text-[#B88E2F]">Rs. 250,000.00</span></div>
        </div>
        <div>
        <CircleX color="#595959" />
        </div>
        </DropdownMenuItem>
        <DropdownMenuSeparator className="mt-16"/>
        <DropdownMenuItem className=" flex gap-4"><span className=" px-4 py-1 border-[1.2px] border-black rounded-full"><Link href="/cart">Cart</Link></span ><span className=" px-4 py-1 border-[1.2px] border-black rounded-full"><Link href="/checkout">Checkout</Link></span><span  className=" px-4 py-1 border-[1.2px] border-black rounded-full"><Link href="/productcomparision">Comparison</Link></span></DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
    }
    />{children}
     <Footer1 />
    </body>
    </html>
  );
}
